require:
  - rubocop-rails
AllCops:
  TargetRubyVersion: 2.7.2
  Exclude:
    - "app/controllers/api/v1/**/*"
    - "app/services/habit_logs_services/habit_logs_filter_service.rb"
    - "spec/requests/api/v1/**/*"
    - "db/**/*"
    - "config/**/*"
    - "script/**/*"
    - "vendor/bundle/**/*"
    - "bin/{bundle,rails,rake}"
    - !ruby/regexp /old_and_unused\.rb$/

Layout/LineLength:
  Max: 120

Layout/TrailingWhitespace:
  Enabled: false

Metrics:
  Enabled: false

Rails/Date:
  Enabled: false

Rails/DynamicFindBy:
  Enabled: false

Rails/FilePath:
  Enabled: false

Rails/TimeZone:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes
