Layout/LineLength:
  Max: 100

Style/StringLiterals:
  EnforcedStyle: double_quotes

Rails/DynamicFindBy:
  Enabled: false

Rails/TimeZone:
  Enabled: false

Layout/TrailingWhitespace:
  Enabled: false
