require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  Exclude:
    - "app/controllers/api/v1/**/*"
    - "spec/requests/api/v1/**/*"

Layout/LineLength:
  Max: 100

Layout/TrailingWhitespace:
  Enabled: false

Metrics:
  Enabled: false

Rails/Date:
  Enabled: false

Rails/DynamicFindBy:
  Enabled: false

Rails/TimeZone:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes
